pipeline {
    agent any 

    stages {
        stage('checkout') {
            steps {
                echo "This is checout branch"
            }
        }
        stage('Test1') {
            steps {
                catchError(stageResult: 'Failure', buildResult: 'SUCCESS') {
                    sh'''
                        echo "This is test1 branch"
                        exit 1
                    '''
                }
        
            }
        }
        stage('test2') {
            steps {
                echo "This is test2 branch"
            }
        }
    }
}